import { type MyCrosswordBasicData } from "~/app/puzzle/[id]/crossword/crossword.type";

export const birthdayCard2021: MyCrosswordBasicData = {
  dimensions: {
    cols: 12,
    rows: 12,
  },
  entries: [
    {
      number: 1,
      direction: "across",
      position: { x: 0, y: 0 },
      group: ["1a", "4a"],
      separatorLocations: { "-": [5] },
      clue: "How old? In your prime!",
      solution: "fifty",
    },
    {
      number: 4,
      direction: "across",
      position: { x: 6, y: 0 },
      group: ["1a", "4a"],
      separatorLocations: {},
      clue: "N/A",
      solution: "nine",
    },
    {
      number: 7,
      direction: "across",
      position: { x: 4, y: 1 },
      clue: "Raw material right in the middle of 25",
      solution: "ore",
    },
    {
      number: 8,
      direction: "across",
      position: { x: 0, y: 2 },
      clue: "Died above place one might sail from",
      solution: "Dover",
    },
    {
      number: 9,
      direction: "across",
      position: { x: 6, y: 2 },
      clue: "Tasty triangle made by Samuel of South Africa",
      solution: "samosa",
    },
    {
      number: 10,
      direction: "across",
      position: { x: 4, y: 3 },
      clue: "Equipment that might fly, losing tail",
      solution: "kit",
    },
    {
      number: 11,
      direction: "across",
      position: { x: 0, y: 4 },
      group: ["11a", "14a"],
      separatorLocations: { ",": [4] },
      clue: "Endure little, perhaps 1 across 4 across past the hour?",
      solution: "last",
    },
    {
      number: 14,
      direction: "across",
      position: { x: 6, y: 4 },
      group: ["11a", "14a"],
      separatorLocations: {},
      clue: "N/A",
      solution: "minute",
    },
    {
      number: 15,
      direction: "across",
      position: { x: 3, y: 5 },
      clue: "In Spain she is a girl",
      solution: "Ella",
    },
    {
      number: 16,
      direction: "across",
      position: { x: 0, y: 6 },
      clue: "Come and feel energised, starting with a drink from here",
      solution: "cafe",
    },
    {
      number: 19,
      direction: "across",
      position: { x: 5, y: 7 },
      clue: "Dodgy pay deal sometimes happens 1 across 4 across days after New Year",
      solution: "leap day",
    },
    {
      number: 20,
      direction: "across",
      position: { x: 0, y: 8 },
      group: ["20a", "25a"],
      separatorLocations: { "-": [5] },
      clue: "1 across 4 across's twin over there in arranged exits",
      solution: "sixty",
    },
    {
      number: 22,
      direction: "across",
      position: { x: 4, y: 9 },
      clue: "Trojans were containing response",
      solution: "answer",
    },
    {
      number: 24,
      direction: "across",
      position: { x: 2, y: 10 },
      clue: "Pull in direction of West",
      solution: "tow",
    },
    {
      number: 25,
      direction: "across",
      position: { x: 0, y: 11 },
      group: ["20a", "25a"],
      separatorLocations: {},
      clue: "N/A",
      solution: "one",
    },
    {
      number: 26,
      direction: "across",
      position: { x: 4, y: 11 },
      clue: "Initially Napoleon oversaw rail department 1 across 4 across in France",
      solution: "Nord",
    },
    {
      number: 27,
      direction: "across",
      position: { x: 9, y: 11 },
      clue: "Reportedly a bit like 1 across 4 across plus 20 25, for instance",
      solution: "sum",
    },
    {
      number: 1,
      direction: "down",
      position: { x: 0, y: 0 },
      group: ["1d", "16d"],
      separatorLocations: { ",": [5] },
      clue: "Idealist force that's gone revolutionary, Prime Minister from 1 across 4 across",
      solution: "Fidel",
    },
    {
      number: 2,
      direction: "down",
      position: { x: 2, y: 0 },
      clue: "There are ten in 1 across and twelve in 20",
      solution: "fives",
    },
    {
      number: 3,
      direction: "down",
      position: { x: 4, y: 0 },
      clue: "A 1 across 4 across could take you here from Wallasey",
      solution: "York",
    },
    {
      number: 4,
      direction: "down",
      position: { x: 6, y: 0 },
      clue: "Avian housewives?",
      solution: "nest-makers",
    },
    {
      number: 5,
      direction: "down",
      position: { x: 8, y: 0 },
      clue: "Designating Nigeria after end of tsunami",
      solution: "naming",
    },
    {
      number: 6,
      direction: "down",
      position: { x: 11, y: 0 },
      clue: "My podiums are confused with element 1 across 4 across",
      solution: "praseodymium",
    },
    {
      number: 12,
      direction: "down",
      position: { x: 1, y: 4 },
      clue: "Range in megagallons",
      solution: "aga",
    },
    {
      number: 13,
      direction: "down",
      position: { x: 3, y: 4 },
      clue: "Starting point when learning to drive?",
      solution: "tee",
    },
    {
      number: 16,
      direction: "down",
      position: { x: 0, y: 6 },
      group: ["1d", "16d"],
      separatorLocations: {},
      clue: "N/A",
      solution: "Castro",
    },
    {
      number: 17,
      direction: "down",
      position: { x: 2, y: 6 },
      clue: "Set consumed, they become obsessed",
      solution: "fixate",
    },
    {
      number: 18,
      direction: "down",
      position: { x: 9, y: 6 },
      clue: "Loves commercial 7s",
      solution: "adores",
    },
    {
      number: 21,
      direction: "down",
      position: { x: 4, y: 8 },
      clue: "Change heading towards North in expression of boredom",
      solution: "yawn",
    },
    {
      number: 23,
      direction: "down",
      position: { x: 7, y: 9 },
      clue: "Soft bundle found in short desert gully",
      solution: "wad",
    },
  ],
};
