import { type MyCrosswordBasicData } from "~/app/puzzle/[id]/crossword/crossword.type";

export const canIt: MyCrosswordBasicData = {
  dimensions: {
    cols: 15,
    rows: 15,
  },
  entries: [
    {
      number: 1,
      direction: "across",
      position: { x: 0, y: 0 },
      clue: "Customised live broadcast",
      solution: "bespoke",
    },
    {
      number: 5,
      direction: "across",
      position: { x: 8, y: 0 },
      clue: "Rich round: inside, a bit of butter, and a bit of egg outside",
      solution: "brioche",
    },
    {
      number: 9,
      direction: "across",
      position: { x: 0, y: 2 },
      clue: "Capital L for the phone",
      solution: "lima",
    },
    {
      number: 10,
      direction: "across",
      position: { x: 5, y: 2 },
      clue: "Drunk after May do, damaging one's reputation",
      solution: "defamatory",
    },
    {
      number: 12,
      direction: "across",
      position: { x: 0, y: 4 },
      clue: "Old close-up of swimmer in the Thames?",
      solution: "grey seal",
    },
    {
      number: 13,
      direction: "across",
      position: { x: 9, y: 4 },
      clue: "Opening two articles in France and Switzerland",
      solution: "launch",
    },
    {
      number: 14,
      direction: "across",
      position: { x: 0, y: 6 },
      clue: "In short, food group hiding love for chocolate substitute",
      solution: "carob",
    },
    {
      number: 16,
      direction: "across",
      position: { x: 6, y: 6 },
      clue: "Quote Spooner's restricted vision",
      solution: "sound bite",
    },
    {
      number: 18,
      direction: "across",
      position: { x: 0, y: 8 },
      clue: "Follow American sandwich reporter",
      solution: "subscribe",
    },
    {
      number: 20,
      direction: "across",
      position: { x: 10, y: 8 },
      clue: "Minor route to comprehensive",
      solution: "broad",
    },
    {
      number: 23,
      direction: "across",
      position: { x: 0, y: 10 },
      clue: "Red bean bag order: amazing stuff packers deliver centrally",
      solution: "adzuki",
    },
    {
      number: 24,
      direction: "across",
      position: { x: 7, y: 10 },
      clue: "Square, if developed, can provide water sources",
      solution: "aquifers",
    },
    {
      number: 26,
      direction: "across",
      position: { x: 0, y: 12 },
      clue: "Old man in Britain's corrupt, taking political compromise",
      solution: "bipartisan",
    },
    {
      number: 27,
      direction: "across",
      position: { x: 11, y: 12 },
      clue: "Dal originally made using natural ghee",
      solution: "mung",
    },
    {
      number: 28,
      direction: "across",
      position: { x: 0, y: 14 },
      clue: "In we've got is tormenting self-centred person",
      solution: "egotist",
    },
    {
      number: 29,
      direction: "across",
      position: { x: 8, y: 14 },
      clue: "Expect page summary",
      solution: "presume",
    },
    {
      number: 2,
      direction: "down",
      position: { x: 1, y: 0 },
      clue: "Country enclosed by barrier it reassembled",
      solution: "Eritrea",
    },
    {
      number: 3,
      direction: "down",
      position: { x: 3, y: 0 },
      clue: "Pale as a mountaintop",
      solution: "peaky",
    },
    {
      number: 4,
      direction: "down",
      position: { x: 5, y: 0 },
      clue: "Organ playing in key :D",
      solution: "kidney",
    },
    {
      number: 6,
      direction: "down",
      position: { x: 9, y: 0 },
      clue: "Head off, picking blackberries and walking",
      solution: "rambling",
    },
    {
      number: 7,
      direction: "down",
      position: { x: 11, y: 0 },
      clue: "Dominate anaesthetist after having revealed one's sexuality",
      solution: "outnumber",
    },
    {
      number: 8,
      direction: "down",
      position: { x: 13, y: 0 },
      clue: "Bring garden tool to Spooner to produce what's baked by Heinz",
      solution: "haricot",
    },
    {
      number: 11,
      direction: "down",
      position: { x: 7, y: 2 },
      clue: "High in energy, like the grid",
      solution: "full of beans",
    },
    {
      number: 15,
      direction: "down",
      position: { x: 3, y: 6 },
      clue: "No word of a lie, clipped article taken in cover-up",
      solution: "obscurant",
    },
    {
      number: 17,
      direction: "down",
      position: { x: 5, y: 7 },
      clue: "Performers get arse and tits out",
      solution: "artistes",
    },
    {
      number: 19,
      direction: "down",
      position: { x: 1, y: 8 },
      clue: "Defeat using control+Z?",
      solution: "undoing",
    },
    {
      number: 21,
      direction: "down",
      position: { x: 13, y: 8 },
      clue: "Any convenient reference or name you make, taking initials only",
      solution: "acronym",
    },
    {
      number: 22,
      direction: "down",
      position: { x: 9, y: 9 },
      clue: "Bannister, perhaps, wooden rail",
      solution: "runner",
    },
    {
      number: 25,
      direction: "down",
      position: { x: 11, y: 10 },
      clue: "Exhaust setter with attention, not quite embracing",
      solution: "fumes",
    },
  ],
};
