import { type MyCrosswordBasicData } from "~/app/puzzle/[id]/crossword/crossword.type";

export const cellService: MyCrosswordBasicData = {
  dimensions: {
    cols: 15,
    rows: 15,
  },
  entries: [
    {
      number: 1,
      direction: "across",
      position: { x: 1, y: 0 },
      group: ["1a", "4a", "6a"],
      separatorLocations: { ",": [4, 8] },
      clue: "Our demand is fair: Earth takes lead",
      solution: "just",
    },
    {
      number: 4,
      direction: "across",
      position: { x: 6, y: 0 },
      group: ["1a", "4a", "6a"],
      separatorLocations: {},
      clue: "N/A",
      solution: "stop",
    },
    {
      number: 6,
      direction: "across",
      position: { x: 11, y: 0 },
      group: ["1a", "4a", "6a"],
      separatorLocations: {},
      clue: "N/A",
      solution: "oil",
    },
    {
      number: 11,
      direction: "across",
      position: { x: 0, y: 2 },
      clue: "Stringed instrument briefly found in United Kingdom and Europe",
      solution: "uke",
    },
    {
      number: 12,
      direction: "across",
      position: { x: 4, y: 2 },
      clue: "Rodent's motorway by Yorkshire river",
      solution: "mouse",
    },
    {
      number: 13,
      direction: "across",
      position: { x: 10, y: 2 },
      clue: "Ceramic country",
      solution: "china",
    },
    {
      number: 14,
      direction: "across",
      position: { x: 8, y: 3 },
      clue: "Grain rhymes oddly",
      solution: "rye",
    },
    {
      number: 15,
      direction: "across",
      position: { x: 0, y: 4 },
      clue: "Easy on vacation, taking leave in balance",
      solution: "equity",
    },
    {
      number: 16,
      direction: "across",
      position: { x: 10, y: 4 },
      clue: "1 brilliant, being decapitated",
      solution: "right",
    },
    {
      number: 19,
      direction: "across",
      position: { x: 6, y: 5 },
      clue: "Solver curtailed twice, spinning toy",
      solution: "yo-yo",
    },
    {
      number: 22,
      direction: "across",
      position: { x: 1, y: 6 },
      clue: "Tree where village remembers hearts",
      solution: "elm",
    },
    {
      number: 25,
      direction: "across",
      position: { x: 9, y: 6 },
      clue: "Lively performance I have",
      solution: "active",
    },
    {
      number: 26,
      direction: "across",
      position: { x: 5, y: 7 },
      clue: "Tides changing, creating changes",
      solution: "edits",
    },
    {
      number: 27,
      direction: "across",
      position: { x: 0, y: 8 },
      clue: "Working behind security measure used by 1,4,6",
      solution: "lock-on",
    },
    {
      number: 28,
      direction: "across",
      position: { x: 11, y: 8 },
      clue: "Used to be perceived backwards",
      solution: "was",
    },
    {
      number: 30,
      direction: "across",
      position: { x: 5, y: 9 },
      clue: 'Retired dogs say "put one foot in front of the other"',
      solution: "step",
    },
    {
      number: 34,
      direction: "across",
      position: { x: 0, y: 10 },
      clue: "Smash serve goes off course",
      solution: "veers",
    },
    {
      number: 37,
      direction: "across",
      position: { x: 9, y: 10 },
      clue: "Psychological harm caused by retro art, you said, by master",
      solution: "trauma",
    },
    {
      number: 38,
      direction: "across",
      position: { x: 4, y: 11 },
      clue: "Age of negative energy returns",
      solution: "eon",
    },
    {
      number: 40,
      direction: "across",
      position: { x: 0, y: 12 },
      clue: 'Brief epitaph ends "not half mature"',
      solution: "ripen",
    },
    {
      number: 41,
      direction: "across",
      position: { x: 6, y: 12 },
      clue: "Synthetic material hidden in many longboats",
      solution: "nylon",
    },
    {
      number: 42,
      direction: "across",
      position: { x: 12, y: 12 },
      clue: "It's enjoyable if you win at the end",
      solution: "fun",
    },
    {
      number: 43,
      direction: "across",
      position: { x: 1, y: 14 },
      clue: "A leftie environmentalist heads to get warm beer",
      solution: "ale",
    },
    {
      number: 44,
      direction: "across",
      position: { x: 5, y: 14 },
      group: ["8d", "44a"],
      separatorLocations: {},
      clue: "N/A",
      solution: "glue",
    },
    {
      number: 45,
      direction: "across",
      position: { x: 10, y: 14 },
      clue: "Take home container for ashes, by the sound of it",
      solution: "earn",
    },
    {
      number: 2,
      direction: "down",
      position: { x: 2, y: 0 },
      clue: "Inside, prune quality is not the same",
      solution: "unequal",
    },
    {
      number: 3,
      direction: "down",
      position: { x: 4, y: 0 },
      group: ["3d", "4d"],
      separatorLocations: { ",": [6] },
      clue: "Very much awake after fruit used by 1,4,6",
      solution: "tomato",
    },
    {
      number: 4,
      direction: "down",
      position: { x: 6, y: 0 },
      group: ["3d", "4d"],
      separatorLocations: {},
      clue: "N/A",
      solution: "soup",
    },
    {
      number: 5,
      direction: "down",
      position: { x: 8, y: 0 },
      clue: "Openly removing Trump's head would be too much",
      solution: "overly",
    },
    {
      number: 7,
      direction: "down",
      position: { x: 12, y: 0 },
      clue: "Decorating one cold gin cocktail",
      solution: "icing",
    },
    {
      number: 8,
      direction: "down",
      position: { x: 0, y: 1 },
      group: ["8d", "44a"],
      separatorLocations: {},
      clue: "Some unruly protestors employ really gloopy liquid, upsetting everyone - primarily used by 1,4,6",
      solution: "super",
    },
    {
      number: 9,
      direction: "down",
      position: { x: 10, y: 1 },
      clue: "Genus of trees seen in cycling race",
      solution: "acer",
    },
    {
      number: 10,
      direction: "down",
      position: { x: 14, y: 1 },
      clue: "4a somewhat hellish alternative",
      solution: "halt",
    },
    {
      number: 17,
      direction: "down",
      position: { x: 11, y: 4 },
      clue: "I won't get lost, following behind",
      solution: "in tow",
    },
    {
      number: 18,
      direction: "down",
      position: { x: 13, y: 4 },
      clue: "Uncovered the live list used by 1,4,6",
      solution: "hi-vis",
    },
    {
      number: 20,
      direction: "down",
      position: { x: 7, y: 5 },
      clue: "6a producer has nothing on air",
      solution: "olive",
    },
    {
      number: 21,
      direction: "down",
      position: { x: 9, y: 5 },
      clue: "Kiln used for drying hops or mixed oats",
      solution: "oast",
    },
    {
      number: 22,
      direction: "down",
      position: { x: 1, y: 6 },
      clue: "Wear down old queen with poem",
      solution: "erode",
    },
    {
      number: 23,
      direction: "down",
      position: { x: 3, y: 6 },
      clue: "Creator's mother beside king and former queen",
      solution: "maker",
    },
    {
      number: 24,
      direction: "down",
      position: { x: 5, y: 6 },
      clue: "The French partners have curved glass",
      solution: "lens",
    },
    {
      number: 29,
      direction: "down",
      position: { x: 12, y: 8 },
      clue: "Water carrier trembling, with five becoming loud",
      solution: "aquifer",
    },
    {
      number: 31,
      direction: "down",
      position: { x: 6, y: 9 },
      clue: "Retreating fast over international organisation used by 1,4,6",
      solution: "tunnel",
    },
    {
      number: 32,
      direction: "down",
      position: { x: 10, y: 9 },
      group: ["32d", "33d"],
      separatorLocations: { ",": [6] },
      clue: "Fruit power isn't used by 1,4,6",
      solution: "orange",
    },
    {
      number: 33,
      direction: "down",
      position: { x: 14, y: 9 },
      group: ["32d", "33d"],
      separatorLocations: {},
      clue: "N/A",
      solution: "paint",
    },
    {
      number: 34,
      direction: "down",
      position: { x: 0, y: 10 },
      group: ["39d", "34d"],
      separatorLocations: {},
      clue: "N/A",
      solution: "vera",
    },
    {
      number: 35,
      direction: "down",
      position: { x: 2, y: 10 },
      clue: "Oust the Spanish under former power",
      solution: "expel",
    },
    {
      number: 36,
      direction: "down",
      position: { x: 4, y: 10 },
      clue: "Deliver to Southend?",
      solution: "send",
    },
    {
      number: 39,
      direction: "down",
      position: { x: 8, y: 11 },
      group: ["39d", "34d"],
      separatorLocations: { ",": [4] },
      clue: "Succulent love in area that's messy",
      solution: "aloe",
    },
  ],
};
