import { type MyCrosswordBasicData } from "~/app/puzzle/[id]/crossword/crossword.type";

export const happyBirthdayIsaac: MyCrosswordBasicData = {
  dimensions: {
    cols: 15,
    rows: 15,
  },
  entries: [
    {
      number: 8,
      direction: "across",
      position: { x: 0, y: 1 },
      clue: "Revolutionary following Parisian who might make this tart",
      solution: "quiche",
    },
    {
      number: 9,
      direction: "across",
      position: { x: 9, y: 1 },
      clue: "Newspaper chief, drunk, rioted",
      solution: "editor",
    },
    {
      number: 10,
      direction: "across",
      position: { x: 5, y: 2 },
      clue: '"Kebab!" exclaimed woman',
      solution: "Donna",
    },
    {
      number: 11,
      direction: "across",
      position: { x: 0, y: 3 },
      clue: "Affront Ned cryptically",
      solution: "offend",
    },
    {
      number: 13,
      direction: "across",
      position: { x: 9, y: 3 },
      clue: "Most offensive German wearing reddish-brown coat",
      solution: "rudest",
    },
    {
      number: 15,
      direction: "across",
      position: { x: 5, y: 4 },
      clue: "Back beside rulers, having drawn",
      solution: "lured",
    },
    {
      number: 16,
      direction: "across",
      position: { x: 0, y: 5 },
      clue: "Enemy baffled about unknown protein",
      solution: "enzyme",
    },
    {
      number: 19,
      direction: "across",
      position: { x: 9, y: 5 },
      clue: "Pokemon's retro hairstyle on hunk",
      solution: "oddish",
    },
    {
      number: 22,
      direction: "across",
      position: { x: 5, y: 6 },
      clue: "Bishop's hat about to raise scope",
      solution: "remit",
    },
    {
      number: 25,
      direction: "across",
      position: { x: 0, y: 7 },
      clue: "Canoe at sea in body of water",
      solution: "ocean",
    },
    {
      number: 26,
      direction: "across",
      position: { x: 10, y: 7 },
      clue: "Neckwear of regressive professors covers nothing",
      solution: "snood",
    },
    {
      number: 27,
      direction: "across",
      position: { x: 5, y: 8 },
      clue: "Tailless infant Kelvin has a Jewish bread",
      solution: "babka",
    },
    {
      number: 30,
      direction: "across",
      position: { x: 0, y: 9 },
      clue: "Heard you had been knocked out of mediaeval challenge by the French elbow",
      solution: "jostle",
    },
    {
      number: 32,
      direction: "across",
      position: { x: 9, y: 9 },
      clue: "Note lost from soak in harbour",
      solution: "marina",
    },
    {
      number: 34,
      direction: "across",
      position: { x: 5, y: 10 },
      clue: "Tax reportedly for embankment",
      solution: "levee",
    },
    {
      number: 35,
      direction: "across",
      position: { x: 0, y: 11 },
      clue: "Handsome man outside old city office",
      solution: "bureau",
    },
    {
      number: 38,
      direction: "across",
      position: { x: 9, y: 11 },
      clue: "Second showing power in handover",
      solution: "replay",
    },
    {
      number: 41,
      direction: "across",
      position: { x: 5, y: 12 },
      clue: "Spanish architect's good car",
      solution: "Gaudi",
    },
    {
      number: 42,
      direction: "across",
      position: { x: 0, y: 13 },
      clue: "You've got to see painter's topless composition!",
      solution: "retina",
    },
    {
      number: 43,
      direction: "across",
      position: { x: 9, y: 13 },
      clue: "Clouds usually make us look, initially?",
      solution: "cumuli",
    },
    {
      number: 1,
      direction: "down",
      position: { x: 1, y: 0 },
      clue: "In Hull having very loud strop",
      solution: "huff",
    },
    {
      number: 2,
      direction: "down",
      position: { x: 3, y: 0 },
      clue: "Hurt back when removing clothes",
      solution: "ache",
    },
    {
      number: 3,
      direction: "down",
      position: { x: 5, y: 0 },
      clue: "Salesman, one reportedly travelling by bicycle",
      solution: "peddler",
    },
    {
      number: 4,
      direction: "down",
      position: { x: 7, y: 0 },
      clue: "Pain at memory of this puzzle, for instance",
      solution: "pangram",
    },
    {
      number: 5,
      direction: "down",
      position: { x: 9, y: 0 },
      clue: "Spooner's treasured sailing boat long ago",
      solution: "year dot",
    },
    {
      number: 6,
      direction: "down",
      position: { x: 11, y: 0 },
      clue: 'Say "tit" or "booby" - to begin with "breast" is rather dull',
      solution: "bird",
    },
    {
      number: 7,
      direction: "down",
      position: { x: 13, y: 0 },
      clue: "Charges for only half of portions",
      solution: "ions",
    },
    {
      number: 12,
      direction: "down",
      position: { x: 2, y: 3 },
      clue: "Zany embellishment for heads from the East?",
      solution: "fez",
    },
    {
      number: 14,
      direction: "down",
      position: { x: 12, y: 3 },
      clue: "Seeing some tolerate discrimination, stands for the opposite",
      solution: "EDI",
    },
    {
      number: 17,
      direction: "down",
      position: { x: 1, y: 5 },
      clue: "Mexican food Anna chooses to eat",
      solution: "nacho",
    },
    {
      number: 18,
      direction: "down",
      position: { x: 3, y: 5 },
      clue: "Point after unknown ingredient of 27",
      solution: "yeast",
    },
    {
      number: 20,
      direction: "down",
      position: { x: 11, y: 5 },
      clue: "One giving name in 37",
      solution: "donor",
    },
    {
      number: 21,
      direction: "down",
      position: { x: 13, y: 5 },
      clue: "Demonstrated by what means infiltrating partners ...",
      solution: "shown",
    },
    {
      number: 23,
      direction: "down",
      position: { x: 6, y: 6 },
      clue: "... are going back in time",
      solution: "era",
    },
    {
      number: 24,
      direction: "down",
      position: { x: 8, y: 6 },
      clue: "One thousand claim right to annoy",
      solution: "irk",
    },
    {
      number: 27,
      direction: "down",
      position: { x: 5, y: 8 },
      clue: "Marine mammals in strange blue fluid",
      solution: "belugas",
    },
    {
      number: 28,
      direction: "down",
      position: { x: 7, y: 8 },
      clue: "5 included in promise to repay account after second rate open-air camping experience",
      solution: "bivouac",
    },
    {
      number: 29,
      direction: "down",
      position: { x: 9, y: 8 },
      clue: "Stormy air came into home of 39",
      solution: "America",
    },
    {
      number: 31,
      direction: "down",
      position: { x: 2, y: 9 },
      clue: "Knight is Irish in part",
      solution: "sir",
    },
    {
      number: 33,
      direction: "down",
      position: { x: 12, y: 9 },
      clue: "Setter is going to be sick",
      solution: "ill",
    },
    {
      number: 36,
      direction: "down",
      position: { x: 1, y: 11 },
      clue: "Accustomed to being exploited",
      solution: "used",
    },
    {
      number: 37,
      direction: "down",
      position: { x: 3, y: 11 },
      clue: "Leave old computers?",
      solution: "exit",
    },
    {
      number: 39,
      direction: "down",
      position: { x: 11, y: 11 },
      clue: "Big cat starts purring under my arm",
      solution: "puma",
    },
    {
      number: 40,
      direction: "down",
      position: { x: 13, y: 11 },
      clue: "Weirdly, Lisa is 33",
      solution: "ails",
    },
  ],
};
