import { type MyCrosswordBasicData } from "~/app/puzzle/[id]/crossword/crossword.type";

export const helloMyNameIs: MyCrosswordBasicData = {
  dimensions: {
    cols: 15,
    rows: 15,
  },
  entries: [
    {
      number: 1,
      direction: "across",
      position: { x: 0, y: 0 },
      clue: '"Come in, thank you" by fashionable host',
      solution: "entertain",
    },
    {
      number: 6,
      direction: "across",
      position: { x: 10, y: 0 },
      clue: "Stone a swinger",
      solution: "agate",
    },
    {
      number: 10,
      direction: "across",
      position: { x: 0, y: 2 },
      clue: "Achieve the top awards in notable firsts?",
      solution: "attain",
    },
    {
      number: 12,
      direction: "across",
      position: { x: 9, y: 2 },
      clue: "Diner takes some tea — terrific!",
      solution: "eater",
    },
    {
      number: 13,
      direction: "across",
      position: { x: 6, y: 3 },
      clue: "Blind worker takes ecstasy",
      solution: "ante",
    },
    {
      number: 15,
      direction: "across",
      position: { x: 0, y: 4 },
      clue: "Go off on one, getting sidetracked",
      solution: "tangent",
    },
    {
      number: 16,
      direction: "across",
      position: { x: 9, y: 4 },
      clue: "In pub, getting fed is natural",
      solution: "innate",
    },
    {
      number: 18,
      direction: "across",
      position: { x: 0, y: 6 },
      clue: "See score before <i>The X Factor</i>",
      solution: "get it",
    },
    {
      number: 20,
      direction: "across",
      position: { x: 6, y: 6 },
      clue: "After remodelling, granite is sharper",
      solution: "tangier",
    },
    {
      number: 23,
      direction: "across",
      position: { x: 2, y: 8 },
      clue: "It brings about Bond, perhaps?",
      solution: "reagent",
    },
    {
      number: 26,
      direction: "across",
      position: { x: 10, y: 8 },
      clue: "Giant screw up, by the sound of it",
      solution: "titan",
    },
    {
      number: 28,
      direction: "across",
      position: { x: 0, y: 10 },
      clue: "Reviewing back-to-front cheesy dish",
      solution: "gratin",
    },
    {
      number: 30,
      direction: "across",
      position: { x: 8, y: 10 },
      clue: "Concerning first in gala, a dry one — hardly!",
      solution: "regatta",
    },
    {
      number: 31,
      direction: "across",
      position: { x: 5, y: 11 },
      clue: "Relative starts graduate role, accepting nepotism",
      solution: "gran",
    },
    {
      number: 33,
      direction: "across",
      position: { x: 1, y: 12 },
      clue: "Europe backing Ireland is weird",
      solution: "eerie",
    },
    {
      number: 34,
      direction: "across",
      position: { x: 9, y: 12 },
      clue: "Farm has good variety",
      solution: "grange",
    },
    {
      number: 36,
      direction: "across",
      position: { x: 0, y: 14 },
      clue: "Bird's remorse after beheading",
      solution: "egret",
    },
    {
      number: 37,
      direction: "across",
      position: { x: 6, y: 14 },
      clue: "Erin woozy after mixing Agent Orange",
      solution: "tangerine",
    },
    {
      number: 2,
      direction: "down",
      position: { x: 1, y: 0 },
      clue: "Ingredient in explosive prevalence of lice?",
      solution: "nitrate",
    },
    {
      number: 3,
      direction: "down",
      position: { x: 3, y: 0 },
      clue: "Some periods are back",
      solution: "era",
    },
    {
      number: 4,
      direction: "down",
      position: { x: 5, y: 0 },
      clue: "Metal prong shortened",
      solution: "tin",
    },
    {
      number: 5,
      direction: "down",
      position: { x: 7, y: 0 },
      clue: "Primarily Islamic region, Armenia's neighbour",
      solution: "Iran",
    },
    {
      number: 7,
      direction: "down",
      position: { x: 11, y: 0 },
      clue: "Offer of admission produces celebratory outburst",
      solution: "get in",
    },
    {
      number: 8,
      direction: "down",
      position: { x: 13, y: 0 },
      clue: "It's found in lungs of smoker, as celeb drops butt",
      solution: "tar",
    },
    {
      number: 9,
      direction: "down",
      position: { x: 9, y: 1 },
      clue: "What's done before driving topless, steering, but not right",
      solution: "teeing",
    },
    {
      number: 11,
      direction: "down",
      position: { x: 4, y: 2 },
      clue: "Resistance to movement trending with European right I initially attempt",
      solution: "inertia",
    },
    {
      number: 13,
      direction: "down",
      position: { x: 6, y: 3 },
      clue: "An idiot having sex",
      solution: "at it",
    },
    {
      number: 14,
      direction: "down",
      position: { x: 14, y: 3 },
      clue: "Earn back a thousand lost for good during stay",
      solution: "regain",
    },
    {
      number: 17,
      direction: "down",
      position: { x: 12, y: 4 },
      clue: "19 reversed legal decision",
      solution: "arret",
    },
    {
      number: 18,
      direction: "down",
      position: { x: 0, y: 6 },
      clue: "Greg's with AA, mending his car here",
      solution: "garage",
    },
    {
      number: 19,
      direction: "down",
      position: { x: 2, y: 6 },
      clue: "Somewhat inter-racial land",
      solution: "terra",
    },
    {
      number: 21,
      direction: "down",
      position: { x: 7, y: 6 },
      clue: "A new name for a woman",
      solution: "Ann",
    },
    {
      number: 22,
      direction: "down",
      position: { x: 10, y: 6 },
      clue: "Cardinal, say, buried in Bury",
      solution: "integer",
    },
    {
      number: 24,
      direction: "down",
      position: { x: 5, y: 8 },
      clue: "Drink half of German spice",
      solution: "ginger",
    },
    {
      number: 25,
      direction: "down",
      position: { x: 8, y: 8 },
      clue: "Audibly rotate bird",
      solution: "tern",
    },
    {
      number: 27,
      direction: "down",
      position: { x: 13, y: 8 },
      clue: "Opposing study into cause of immune response",
      solution: "antigen",
    },
    {
      number: 29,
      direction: "down",
      position: { x: 3, y: 10 },
      clue: "Briefly aim at Highlander's shield",
      solution: "targe",
    },
    {
      number: 32,
      direction: "down",
      position: { x: 7, y: 11 },
      clue: "A breezier report",
      solution: "area",
    },
    {
      number: 33,
      direction: "down",
      position: { x: 1, y: 12 },
      clue: "You'll look silly with this on your face",
      solution: "egg",
    },
    {
      number: 34,
      direction: "down",
      position: { x: 9, y: 12 },
      clue: "Crack nameless criminal group",
      solution: "gag",
    },
    {
      number: 35,
      direction: "down",
      position: { x: 11, y: 12 },
      clue: "Just avoiding loud atmosphere",
      solution: "air",
    },
  ],
};
