import { MyCrosswordBasicData } from "~/app/puzzle/[id]/crossword/crossword.type";

export const insiders: MyCrosswordBasicData = {
  dimensions: {
    cols: 15,
    rows: 15,
  },
  entries: [
    {
      number: 1,
      direction: "across",
      position: { x: 0, y: 0 },
      clue: "Vibrant company has 54⅓ fulfilled",
      solution: "colourful",
    },
    {
      number: 9,
      direction: "across",
      position: { x: 8, y: 1 },
      clue: "Commercial sheep worker is resolute",
      solution: "adamant",
    },
    {
      number: 10,
      direction: "across",
      position: { x: 0, y: 2 },
      clue: "Perrins' partner sent back a slippery fish",
      solution: "Lea",
    },
    {
      number: 11,
      direction: "across",
      position: { x: 4, y: 2 },
      clue: "One who sticks to rule e.g. working",
      solution: "gluer",
    },
    {
      number: 12,
      direction: "across",
      position: { x: 2, y: 3 },
      clue: "Cereal gets some very excited",
      solution: "rye",
    },
    {
      number: 14,
      direction: "across",
      position: { x: 8, y: 3 },
      clue: "Put 27,27a as police officer introduces new penalty",
      solution: "confine",
    },
    {
      number: 15,
      direction: "across",
      position: { x: 5, y: 4 },
      clue: "Compiler present briefly in grid",
      solution: "mesh",
    },
    {
      number: 17,
      direction: "across",
      position: { x: 0, y: 5 },
      clue: "Wave off pill rep",
      solution: "ripple",
    },
    {
      number: 20,
      direction: "across",
      position: { x: 11, y: 5 },
      clue: "A flower's friend",
      solution: "ally",
    },
    {
      number: 22,
      direction: "across",
      position: { x: 7, y: 6 },
      clue: "Come out on top of womb-mate",
      solution: "win",
    },
    {
      number: 23,
      direction: "across",
      position: { x: 0, y: 7 },
      clue: "User on acid diet, tripping, lacks energy",
      solution: "addict",
    },
    {
      number: 24,
      direction: "across",
      position: { x: 9, y: 7 },
      clue: "Manage in court following serious charge",
      solution: "direct",
    },
    {
      number: 25,
      direction: "across",
      position: { x: 5, y: 8 },
      clue: "Regulation makes legal advisers' accountants worry initially",
      solution: "law",
    },
    {
      number: 27,
      direction: "across",
      position: { x: 0, y: 9 },
      group: ["27d", "27a"],
      clue: "See 27d",
      solution: "bars",
    },
    {
      number: 29,
      direction: "across",
      position: { x: 9, y: 9 },
      clue: "A right shame to open with instrumental",
      solution: "guitar",
    },
    {
      number: 32,
      direction: "across",
      position: { x: 6, y: 10 },
      clue: "Repeat concerning act",
      solution: "redo",
    },
    {
      number: 34,
      direction: "across",
      position: { x: 0, y: 11 },
      clue: "Skips article and its retraction - hallelujah!",
      solution: "hosanna",
    },
    {
      number: 35,
      direction: "across",
      position: { x: 10, y: 11 },
      clue: "Lowland bracken",
      solution: "fen",
    },
    {
      number: 37,
      direction: "across",
      position: { x: 6, y: 12 },
      clue: "Doctor, I struggle with ambition",
      solution: "drive",
    },
    {
      number: 38,
      direction: "across",
      position: { x: 12, y: 12 },
      clue: "Submerge mighty tree",
      solution: "oak",
    },
    {
      number: 39,
      direction: "across",
      position: { x: 0, y: 13 },
      clue: "At first no one is really very adept, never achieving transcendence",
      solution: "nirvana",
    },
    {
      number: 40,
      direction: "across",
      position: { x: 6, y: 14 },
      clue: "<i>Great North</i> cast received acknowledgement on the radio",
      solution: "roger that",
    },
    {
      number: 1,
      direction: "down",
      position: { x: 0, y: 0 },
      clue: "The Spanish hidden in empty basement",
      solution: "cellar",
    },
    {
      number: 2,
      direction: "down",
      position: { x: 2, y: 0 },
      clue: "Dishonest person's undressing flirt - tart!",
      solution: "liar",
    },
    {
      number: 3,
      direction: "down",
      position: { x: 4, y: 0 },
      clue: "Powerful rush of desire",
      solution: "urge",
    },
    {
      number: 4,
      direction: "down",
      position: { x: 6, y: 0 },
      clue: "It's pure luck - illness firstly kills leader of enemy",
      solution: "fluke",
    },
    {
      number: 5,
      direction: "down",
      position: { x: 8, y: 0 },
      clue: "Pine's left bend",
      solution: "larch",
    },
    {
      number: 6,
      direction: "down",
      position: { x: 10, y: 0 },
      group: ["6d", "21d"],
      clue: "Grievously insult a spy agency's place in the Caribbean",
      solution: "Saint",
    },
    {
      number: 7,
      direction: "down",
      position: { x: 12, y: 0 },
      clue: "He was thrown to the lions, nailed, kaput",
      solution: "Daniel",
    },
    {
      number: 8,
      direction: "down",
      position: { x: 14, y: 0 },
      clue: "Determined, cunning, taking a stand",
      solution: "steely",
    },
    {
      number: 13,
      direction: "down",
      position: { x: 3, y: 3 },
      clue: "Trendy professionals say yes to pastries…",
      solution: "yuppies",
    },
    {
      number: 15,
      direction: "down",
      position: { x: 5, y: 4 },
      clue: "...without French and melt in crisis - showing a lack of this?",
      solution: "mettle",
    },
    {
      number: 16,
      direction: "down",
      position: { x: 7, y: 4 },
      clue: "Mother of swine spread seed",
      solution: "sow",
    },
    {
      number: 18,
      direction: "down",
      position: { x: 1, y: 5 },
      clue: "Republic to support Northern Ireland's return",
      solution: "India",
    },
    {
      number: 19,
      direction: "down",
      position: { x: 9, y: 5 },
      clue: "In Germany, I turn a bluish colour",
      solution: "indigo",
    },
    {
      number: 20,
      direction: "down",
      position: { x: 11, y: 5 },
      clue: "Carrier of song lyric",
      solution: "airline",
    },
    {
      number: 21,
      direction: "down",
      position: { x: 13, y: 5 },
      group: ["6d", "21d"],
      clue: "See 6",
      solution: "Lucia",
    },
    {
      number: 26,
      direction: "down",
      position: { x: 7, y: 8 },
      clue: "Lefts watch on, expressing sorrow",
      solution: "woe",
    },
    {
      number: 27,
      direction: "down",
      position: { x: 0, y: 9 },
      group: ["27d", "27a"],
      clue: "Locked up, like a dozen people are in this grid",
      solution: "behind",
    },
    {
      number: 28,
      direction: "down",
      position: { x: 2, y: 9 },
      clue: "War to address drama over sovereignty ends only with help of prayer",
      solution: "rosary",
    },
    {
      number: 30,
      direction: "down",
      position: { x: 14, y: 9 },
      clue: "Criminal conspiracy creating commotion",
      solution: "racket",
    },
    {
      number: 31,
      direction: "down",
      position: { x: 4, y: 10 },
      clue: "Requirement for making bread?",
      solution: "knead",
    },
    {
      number: 32,
      direction: "down",
      position: { x: 6, y: 10 },
      clue: "System that detects aircraft in both directions",
      solution: "radar",
    },
    {
      number: 33,
      direction: "down",
      position: { x: 8, y: 10 },
      clue: "Body in grave, partially decaying",
      solution: "dying",
    },
    {
      number: 35,
      direction: "down",
      position: { x: 10, y: 11 },
      clue: "Listener goes after loud alarm",
      solution: "fear",
    },
    {
      number: 36,
      direction: "down",
      position: { x: 12, y: 11 },
      clue: "Ark builder's no amateur - hull's top!",
      solution: "Noah",
    },
  ],
};
