import { MyCrosswordBasicData } from "~/app/puzzle/[id]/crossword/crossword.type";

export const partingGift: MyCrosswordBasicData = {
  dimensions: {
    cols: 13,
    rows: 13,
  },
  entries: [
    {
      number: 1,
      direction: "across",
      position: { x: 0, y: 0 },
      clue: "Nice extra greeting",
      solution: "goodbye",
    },
    {
      number: 4,
      direction: "across",
      position: { x: 8, y: 0 },
      clue: "1 to perish in Australia",
      solution: "adieu",
    },
    {
      number: 8,
      direction: "across",
      position: { x: 0, y: 2 },
      clue: "1 also gets around a lot, though not single",
      solution: "toodle-oo",
    },
    {
      number: 9,
      direction: "across",
      position: { x: 9, y: 2 },
      clue: "Over-flatten seaweed",
      solution: "nori",
    },
    {
      number: 10,
      direction: "across",
      position: { x: 7, y: 3 },
      clue: "Manipulate equipment",
      solution: "rig",
    },
    {
      number: 11,
      direction: "across",
      position: { x: 0, y: 4 },
      clue: "Wasting time, Master Tom? Cheeky monkey!",
      solution: "marmoset",
    },
    {
      number: 15,
      direction: "across",
      position: { x: 9, y: 4 },
      clue: "Search, buy a belt, and return it - here?",
      solution: "Ebay",
    },
    {
      number: 17,
      direction: "across",
      position: { x: 0, y: 6 },
      clue: "Meandering talk's half lost to cartoon 1",
      solution: "that's all folks",
    },
    {
      number: 18,
      direction: "across",
      position: { x: 0, y: 8 },
      clue: "Opposed to infanticide, to an extent",
      solution: "anti",
    },
    {
      number: 19,
      direction: "across",
      position: { x: 5, y: 8 },
      clue: "Torpedos destroyed part of entrance",
      solution: "doorstep",
    },
    {
      number: 23,
      direction: "across",
      position: { x: 3, y: 9 },
      clue: "Low secondo?",
      solution: "moo",
    },
    {
      number: 24,
      direction: "across",
      position: { x: 0, y: 10 },
      clue: "Repetitive precursor to foxtrot?",
      solution: "echo",
    },
    {
      number: 25,
      direction: "across",
      position: { x: 5, y: 10 },
      clue: "1 sounds lovely and healthy",
      solution: "farewell",
    },
    {
      number: 26,
      direction: "across",
      position: { x: 0, y: 12 },
      clue: "1's made easy with injection of drug",
      solution: "see ya",
    },
    {
      number: 27,
      direction: "across",
      position: { x: 6, y: 12 },
      clue: "1 breakfast food",
      solution: "cheerio",
    },
    {
      number: 1,
      direction: "down",
      position: { x: 0, y: 0 },
      clue: "Heads off Germany's expansion through Europe, marching with battle cry",
      solution: "get 'em",
    },
    {
      number: 2,
      direction: "down",
      position: { x: 2, y: 0 },
      clue: "Funk band has serious following",
      solution: "odour",
    },
    {
      number: 3,
      direction: "down",
      position: { x: 4, y: 0 },
      clue: "Hobbit told to charge with weapon",
      solution: "Bilbo",
    },
    {
      number: 5,
      direction: "down",
      position: { x: 9, y: 0 },
      clue: "Party in America harnesses rage, posing a threat",
      solution: "dangerous",
    },
    {
      number: 6,
      direction: "down",
      position: { x: 12, y: 0 },
      clue: "Gather peacekeepers when facing unknown",
      solution: "unify",
    },
    {
      number: 7,
      direction: "down",
      position: { x: 7, y: 1 },
      clue: "You can go anywhere with this!",
      solution: "portaloo",
    },
    {
      number: 12,
      direction: "down",
      position: { x: 1, y: 4 },
      clue: "When bird is greyish",
      solution: "ashen",
    },
    {
      number: 13,
      direction: "down",
      position: { x: 3, y: 4 },
      clue: "Could holding lean on union?",
      solution: "matrimony",
    },
    {
      number: 14,
      direction: "down",
      position: { x: 5, y: 4 },
      clue: "Put away unresolved conflict",
      solution: "stand-off",
    },
    {
      number: 16,
      direction: "down",
      position: { x: 11, y: 4 },
      clue: "Shank - leg part?",
      solution: "ankle",
    },
    {
      number: 18,
      direction: "down",
      position: { x: 0, y: 8 },
      clue: "Claims by one who's thrifty head-to-toe",
      solution: "avers",
    },
    {
      number: 20,
      direction: "down",
      position: { x: 8, y: 8 },
      clue: "Thread exposing Green I've met",
      solution: "reeve",
    },
    {
      number: 21,
      direction: "down",
      position: { x: 10, y: 8 },
      clue: "Not our time to rent, with energy going up",
      solution: "their",
    },
    {
      number: 22,
      direction: "down",
      position: { x: 12, y: 8 },
      clue: "1 in mint condition",
      solution: "polio",
    },
  ],
};
