import { type MyCrosswordBasicData } from "~/app/puzzle/[id]/crossword/crossword.type";

export const paws: MyCrosswordBasicData = {
  dimensions: {
    cols: 23,
    rows: 23,
  },
  entries: [
    {
      number: 1,
      direction: "across",
      position: { x: 1, y: 0 },
      solution: "straighten up",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 8,
      direction: "across",
      position: { x: 14, y: 0 },
      solution: "Aunt Lucy",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 14,
      direction: "across",
      position: { x: 0, y: 2 },
      solution: "uterine",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 15,
      direction: "across",
      position: { x: 8, y: 2 },
      solution: "pilgrim",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 16,
      direction: "across",
      position: { x: 16, y: 2 },
      solution: "beehive",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 17,
      direction: "across",
      position: { x: 0, y: 4 },
      solution: "first reading",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 20,
      direction: "across",
      position: { x: 13, y: 4 },
      solution: "grub",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 22,
      direction: "across",
      position: { x: 18, y: 4 },
      solution: "naked",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 24,
      direction: "across",
      position: { x: 0, y: 6 },
      solution: "lower school",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 28,
      direction: "across",
      position: { x: 12, y: 6 },
      solution: "alb",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 29,
      direction: "across",
      position: { x: 16, y: 6 },
      solution: "abandon",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 30,
      direction: "across",
      position: { x: 0, y: 8 },
      solution: "or something like that",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 32,
      direction: "across",
      position: { x: 20, y: 8 },
      group: ["25d", "32a"],
      separatorLocations: {},
      solution: "out",
      clue: "",
    },
    {
      number: 33,
      direction: "across",
      position: { x: 0, y: 10 },
      solution: "Thirty-Two Windsor Gardens",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 38,
      direction: "across",
      position: { x: 0, y: 12 },
      solution: "please look after this bear",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 42,
      direction: "across",
      position: { x: 0, y: 14 },
      solution: "dot",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 43,
      direction: "across",
      position: { x: 4, y: 14 },
      solution: "marmalade sandwiches",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 47,
      direction: "across",
      position: { x: 0, y: 16 },
      solution: "indulge",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 49,
      direction: "across",
      position: { x: 8, y: 16 },
      solution: "due",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 50,
      direction: "across",
      position: { x: 12, y: 16 },
      solution: "boysenberry",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 54,
      direction: "across",
      position: { x: 0, y: 18 },
      solution: "gorge",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 55,
      direction: "across",
      position: { x: 6, y: 18 },
      solution: "shop",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 56,
      direction: "across",
      position: { x: 11, y: 18 },
      solution: "East China Sea",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 61,
      direction: "across",
      position: { x: 0, y: 20 },
      solution: "oceanic",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 63,
      direction: "across",
      position: { x: 8, y: 20 },
      solution: "initial",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 64,
      direction: "across",
      position: { x: 16, y: 20 },
      solution: "pinball",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 65,
      direction: "across",
      position: { x: 1, y: 22 },
      solution: "straddle",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 66,
      direction: "across",
      position: { x: 10, y: 22 },
      solution: "demonstrated",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 2,
      direction: "down",
      position: { x: 2, y: 0 },
      solution: "The Browns",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 3,
      direction: "down",
      position: { x: 4, y: 0 },
      solution: "aviator",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 4,
      direction: "down",
      position: { x: 6, y: 0 },
      solution: "geese",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 5,
      direction: "down",
      position: { x: 8, y: 0 },
      solution: "tepid",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 6,
      direction: "down",
      position: { x: 10, y: 0 },
      solution: "nylon",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 7,
      direction: "down",
      position: { x: 12, y: 0 },
      group: ["48d", "7d"],
      separatorLocations: {},
      solution: "Peru",
      clue: "",
    },
    {
      number: 8,
      direction: "down",
      position: { x: 14, y: 0 },
      solution: "admirable",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 9,
      direction: "down",
      position: { x: 16, y: 0 },
      solution: "nib",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 10,
      direction: "down",
      position: { x: 18, y: 0 },
      solution: "lie in wait",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 11,
      direction: "down",
      position: { x: 20, y: 0 },
      solution: "clicked",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 12,
      direction: "down",
      position: { x: 0, y: 1 },
      solution: "duffel coat",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 13,
      direction: "down",
      position: { x: 22, y: 1 },
      solution: "tendonitis",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 18,
      direction: "down",
      position: { x: 7, y: 4 },
      solution: "ash",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 19,
      direction: "down",
      position: { x: 9, y: 4 },
      solution: "I do",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 21,
      direction: "down",
      position: { x: 16, y: 4 },
      solution: "bear hug",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 23,
      direction: "down",
      position: { x: 12, y: 5 },
      solution: "samizdat",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 25,
      direction: "down",
      position: { x: 6, y: 6 },
      group: ["25d", "32a"],
      separatorLocations: { ",": [3, 5] },
      solution: "cut it",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 26,
      direction: "down",
      position: { x: 8, y: 6 },
      solution: "Orinoco",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 27,
      direction: "down",
      position: { x: 10, y: 6 },
      solution: "lug",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 31,
      direction: "down",
      position: { x: 4, y: 8 },
      solution: "mates",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 32,
      direction: "down",
      position: { x: 20, y: 8 },
      solution: "obese",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 34,
      direction: "down",
      position: { x: 2, y: 10 },
      solution: "inert",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 35,
      direction: "down",
      position: { x: 10, y: 10 },
      solution: "imamates",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 36,
      direction: "down",
      position: { x: 14, y: 10 },
      solution: "Our Lady",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 37,
      direction: "down",
      position: { x: 18, y: 10 },
      solution: "rishi",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 38,
      direction: "down",
      position: { x: 0, y: 12 },
      solution: "Paddington",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 39,
      direction: "down",
      position: { x: 6, y: 12 },
      solution: "lurkers",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 40,
      direction: "down",
      position: { x: 16, y: 12 },
      solution: "hedge",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 41,
      direction: "down",
      position: { x: 22, y: 12 },
      solution: "rusty nails",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 43,
      direction: "down",
      position: { x: 4, y: 14 },
      solution: "millennia",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 44,
      direction: "down",
      position: { x: 8, y: 14 },
      group: ["60d", "44d"],
      separatorLocations: {},
      solution: "and polite",
      clue: "",
    },
    {
      number: 45,
      direction: "down",
      position: { x: 12, y: 14 },
      solution: "ebb",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 46,
      direction: "down",
      position: { x: 20, y: 14 },
      solution: "hard stare",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 48,
      direction: "down",
      position: { x: 2, y: 16 },
      group: ["48d", "7d"],
      separatorLocations: { ",": [7] },
      solution: "Darkest",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 51,
      direction: "down",
      position: { x: 13, y: 16 },
      solution: "ops",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 52,
      direction: "down",
      position: { x: 15, y: 16 },
      solution: "sac",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 53,
      direction: "down",
      position: { x: 18, y: 16 },
      solution: "bonanza",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 57,
      direction: "down",
      position: { x: 12, y: 18 },
      solution: "axiom",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 58,
      direction: "down",
      position: { x: 14, y: 18 },
      solution: "talon",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 59,
      direction: "down",
      position: { x: 16, y: 18 },
      solution: "hop it",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 60,
      direction: "down",
      position: { x: 10, y: 19 },
      group: ["60d", "44d"],
      separatorLocations: { ",": [4, 7] },
      solution: "kind",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
    {
      number: 62,
      direction: "down",
      position: { x: 6, y: 20 },
      solution: "cod",
      clue: "",
      clueWithDefinitionUnderlined: "",
      explanation: "",
    },
  ],
};
