import { MyCrosswordBasicData } from "~/app/puzzle/[id]/crossword/crossword.type";

export const insiders: MyCrosswordBasicData = {
  dimensions: {
    cols: 15,
    rows: 15,
  },
  entries: [
    {
      clue: "Drink (alcohol-free, that is) to suit companion (7)",
      group: ["1-across"],
      number: 1,
      position: {
        x: 0,
        y: 0,
      },
      solution: "NECKTIE",
      direction: "across",
      explanation: "[T] NECK (drink) + TT (alcohol-free) + IE (that is)",
      humanNumber: "1",
      separatorLocations: {},
    },
    {
      clue: "Leaves work at PR agency to have children (a couple of each) (7)",
      group: ["5-across"],
      number: 5,
      position: {
        x: 8,
        y: 0,
      },
      solution: "SPINACH",
      direction: "across",
      explanation:
        "[H] SPIN (work at PR agency) + first two letters of (a couple of each) HAve CHildren ",
      humanNumber: "5",
      separatorLocations: {},
    },
    {
      clue: "Quick way to get a spouse (5)",
      group: ["8-across"],
      number: 8,
      position: {
        x: 0,
        y: 2,
      },
      solution: "SWIFT",
      direction: "across",
      explanation: "[E] ST (way = street) around (to get) WIFE (a spouse)",
      humanNumber: "8",
      separatorLocations: {},
    },
    {
      clue: "Very low after employee passes on so easily (5,4)",
      group: ["9-across"],
      number: 9,
      position: {
        x: 6,
        y: 2,
      },
      solution: "HANDSDOWN",
      direction: "across",
      explanation: "[O] SO DOWN (very low) after HAND (employee)",
      humanNumber: "9",
      separatorLocations: {
        ",": [5],
      },
    },
    {
      clue: "Prison club one disrupted (8,5)",
      group: ["11-across"],
      number: 11,
      position: {
        x: 0,
        y: 4,
      },
      solution: "RUNCIBLESPOON",
      direction: "across",
      explanation: "[Theme word] Anagram (disrupted) of PRISON CLUB ONE",
      humanNumber: "11",
      separatorLocations: {
        ",": [8],
      },
    },
    {
      clue: "Graphical user interface with trash (6)",
      group: ["13-across"],
      number: 13,
      position: {
        x: 0,
        y: 6,
      },
      solution: "GUITAR",
      direction: "across",
      explanation: "[Theme word] GUI (graphical user interface) + TAR (trash)",
      humanNumber: "13",
      separatorLocations: {},
    },
    {
      clue: "Sounds like the cat takes special space in dining hall (4,4)",
      group: ["16-across"],
      number: 16,
      position: {
        x: 7,
        y: 6,
      },
      solution: "MESSROOM",
      direction: "across",
      explanation:
        "[W] MEWS (sounds like the cat) + S (special) + ROOM (space)",
      humanNumber: "16",
      separatorLocations: {
        ",": [4],
      },
    },
    {
      clue: "Order of events is up to compiler to file (8)",
      group: ["18-across"],
      number: 18,
      position: {
        x: 0,
        y: 8,
      },
      solution: "TIMELINE",
      direction: "across",
      explanation: "[L] TIL (up to = until) + ME (compiler) + LINE (file)",
      humanNumber: "18",
      separatorLocations: {},
    },
    {
      clue: "Coy prat circulating Bitcoin? (6)",
      group: ["19-across"],
      number: 19,
      position: {
        x: 9,
        y: 8,
      },
      solution: "CRYPTO",
      direction: "across",
      explanation: "[A] Anagram (circulating) of COY PRAT",
      humanNumber: "19",
      separatorLocations: {},
    },
    {
      clue: "Famous group with hit record (4-5,4)",
      group: ["24-across"],
      number: 24,
      position: {
        x: 2,
        y: 10,
      },
      solution: "FIVEPOUNDNOTE",
      direction: "across",
      explanation:
        "[Theme word] FIVE (famous group - The Famous Five) + POUND (hit) + NOTE (record)",
      humanNumber: "24",
      separatorLocations: {
        ",": [9],
        "-": [4],
      },
    },
    {
      clue: 'Voiceover: "sodium, right now, has restricted supply" (9)',
      group: ["26-across"],
      number: 26,
      position: {
        x: 0,
        y: 12,
      },
      solution: "NARRATION",
      direction: "across",
      explanation:
        "[N] NA (sodium) + RN (right now) + RATION (restricted supply)",
      humanNumber: "26",
      separatorLocations: {},
    },
    {
      clue: "Love of money - it's the root of evil, being absorbed by empty god - only half spared (5)",
      group: ["27-across"],
      number: 27,
      position: {
        x: 10,
        y: 12,
      },
      solution: "GREED",
      direction: "across",
      explanation:
        "[D] First letter (root) of Evil inside (being absorbed by) outside letters (empty) of GoD + half of spaRED",
      humanNumber: "27",
      separatorLocations: {},
    },
    {
      clue: "Words about one late coming out of the pit at Philadelphia (7)",
      group: ["28-across"],
      number: 28,
      position: {
        x: 0,
        y: 14,
      },
      solution: "EPITAPH",
      direction: "across",
      explanation: "[T] Hidden in (coming out of) thE PIT AT PHiladelphia",
      humanNumber: "28",
      separatorLocations: {},
    },
    {
      clue: "Turn up with old man, your old feeling the same (7)",
      group: ["29-across"],
      number: 29,
      position: {
        x: 8,
        y: 14,
      },
      solution: "EMPATHY",
      direction: "across",
      explanation: "[H] HEM (turn up) + PA (old man) + THY (your old)",
      humanNumber: "29",
      separatorLocations: {},
    },
    {
      clue: "Bristle going under butt in hanky (4,3)",
      group: ["1-down"],
      number: 1,
      position: {
        x: 0,
        y: 0,
      },
      solution: "NOSERAG",
      direction: "down",
      explanation: "[E] RAGE (bristle) under NOSE (butt in)",
      humanNumber: "1",
      separatorLocations: {
        ",": [4],
      },
    },
    {
      clue: "Red Cross helps international aid NGOs to provide items initially (7)",
      group: ["2-down"],
      number: 2,
      position: {
        x: 2,
        y: 0,
      },
      solution: "CHIANTI",
      direction: "down",
      explanation:
        "[P] First letters (initially) of Cross Helps International Aid Ngos To Provide Items",
      humanNumber: "2",
      separatorLocations: {},
    },
    {
      clue: "Ballet skirt? Bring it back for all performers (5)",
      group: ["3-down"],
      number: 3,
      position: {
        x: 4,
        y: 0,
      },
      solution: "TUTTI",
      direction: "down",
      explanation: "[U] TUTU (ballet skirt) + reversal (bring ... back) of IT",
      humanNumber: "3",
      separatorLocations: {},
    },
    {
      clue: "Let out wind with sound, following coitus (6)",
      group: ["4-down"],
      number: 4,
      position: {
        x: 6,
        y: 0,
      },
      solution: "EXHALE",
      direction: "down",
      explanation:
        "[S] HALE (sound = in good health) after (following) SEX (coitus)",
      humanNumber: "4",
      separatorLocations: {},
    },
    {
      clue: "Left for Rome, where sibling holds positions of influence (8)",
      group: ["5-down"],
      number: 5,
      position: {
        x: 8,
        y: 0,
      },
      solution: "SINISTER",
      direction: "down",
      explanation:
        "[S] SISTER (sibling) around (holds) INS (position of influence)",
      humanNumber: "5",
      separatorLocations: {},
    },
    {
      clue: "Nut throwing crayon (5)",
      group: ["6-down"],
      number: 6,
      position: {
        x: 12,
        y: 0,
      },
      solution: "ACORN",
      direction: "down",
      explanation: "[Y] Anagram (throwing) of CRAYON",
      humanNumber: "6",
      separatorLocations: {},
    },
    {
      clue: "Perfect year (5)",
      group: ["7-down"],
      number: 7,
      position: {
        x: 14,
        y: 0,
      },
      solution: "HONEY",
      direction: "down",
      explanation: "[Theme word] HONE (perfect) + Y (year)",
      humanNumber: "7",
      separatorLocations: {},
    },
    {
      clue: "Ship carrying pony - not quite getting my support financially (7)",
      group: ["10-down"],
      number: 10,
      position: {
        x: 10,
        y: 2,
      },
      solution: "SPONSOR",
      direction: "down",
      explanation:
        "[C] SS (ship) around (carrying) PONy missing last letter (not quite) + COR (my)",
      humanNumber: "10",
      separatorLocations: {},
    },
    {
      clue: "Oddly buoyant (4)",
      group: ["12-down"],
      number: 12,
      position: {
        x: 13,
        y: 5,
      },
      solution: "BOAT",
      direction: "down",
      explanation: "[Theme word] Odd letters of (oddly) BuOyAnT",
      humanNumber: "12",
      separatorLocations: {},
    },
    {
      clue: "Squad cycling at university (4)",
      group: ["14-down"],
      number: 14,
      position: {
        x: 1,
        y: 6,
      },
      solution: "UNIT",
      direction: "down",
      explanation: "[A] AT UNI (at university) cycling AT to the end",
      humanNumber: "14",
      separatorLocations: {},
    },
    {
      clue: "River deposits everything, you heard, with time passing by (7)",
      group: ["15-down"],
      number: 15,
      position: {
        x: 4,
        y: 6,
      },
      solution: "ALLUVIA",
      direction: "down",
      explanation:
        "[T] ALL (everything) + U (you heard) + T (time) + VIA (passing by)",
      humanNumber: "15",
      separatorLocations: {},
    },
    {
      clue: "Severus's expression of disdain showing irritability (8)",
      group: ["17-down"],
      number: 17,
      position: {
        x: 6,
        y: 7,
      },
      solution: "SNAPPISH",
      direction: "down",
      explanation: "[E] SNAPE (Severus) + PISH (expression of disdain)",
      humanNumber: "17",
      separatorLocations: {},
    },
    {
      clue: "With mobile network dropping out, kick out commoner before producing forecast (7)",
      group: ["20-down"],
      number: 20,
      position: {
        x: 12,
        y: 8,
      },
      solution: "PROJECT",
      direction: "down",
      explanation:
        "[L] PROLE (commoner) before EJECT (kick out), minus (with ... dropping out) EE (mobile network)",
      humanNumber: "20",
      separatorLocations: {},
    },
    {
      clue: "When anyone can have a look around, work has to stop, yes (4,3)",
      group: ["21-down"],
      number: 21,
      position: {
        x: 14,
        y: 8,
      },
      solution: "OPENDAY",
      direction: "down",
      explanation: "[E] OP (work) + END (to stop) + AYE (yes)",
      humanNumber: "21",
      separatorLocations: {
        ",": [4],
      },
    },
    {
      clue: "Starts to question understanding: is Norway considered European? (6)",
      group: ["22-down"],
      number: 22,
      position: {
        x: 8,
        y: 9,
      },
      solution: "QUINCE",
      direction: "down",
      explanation:
        "[Theme word] First letters of (starts to) Question Understanding Is Norway Considered European",
      humanNumber: "22",
      separatorLocations: {},
    },
    {
      clue: "Cinema struggling, having lost core of finance (5)",
      group: ["23-down"],
      number: 23,
      position: {
        x: 0,
        y: 10,
      },
      solution: "MINCE",
      direction: "down",
      explanation:
        "[Theme word] Anagram (struggling) of CINEMA minus (having lost) middle letter (core) of finAnce",
      humanNumber: "23",
      separatorLocations: {},
    },
    {
      clue: "Language from afar - a Sinitic fragment (5)",
      group: ["24-down"],
      number: 24,
      position: {
        x: 2,
        y: 10,
      },
      solution: "FARSI",
      direction: "down",
      explanation: "[A] Hidden (fragment) in aFAR A SInitic",
      humanNumber: "24",
      separatorLocations: {},
    },
    {
      clue: "Dutch cobble together mine (3,2)",
      group: ["25-down"],
      number: 25,
      position: {
        x: 10,
        y: 10,
      },
      solution: "DIGUP",
      direction: "down",
      explanation: "[R] D (Dutch) + RIG UP (cobble together)",
      humanNumber: "25",
      separatorLocations: {
        ",": [3],
      },
    },
  ],
};
