name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm install
      - name: Install browsers
        run: npx playwright install --with-deps
      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_IMAGES_BLOB_PREFIX: ${{ secrets.NEXT_PUBLIC_IMAGES_BLOB_PREFIX }}
          NEXT_PUBLIC_PRINT_BLOB_PREFIX: ${{ secrets.NEXT_PUBLIC_PRINT_BLOB_PREFIX }}
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
